### ISSUE TITLE
Installation instructions link to 404

### ISSUE THREAD

**Issue by jonathonf** [Metaxal/MrEd-Designer#1]
The installation instructions link (http://pkgs.racket-lang.org/info/mred-designer) returns a 404 error.

**Comment by Metaxal** [comment]
Thanks for the report. It should be fixed now.

**Comment by jonathonf** [comment]
Installation works nicely - but how do you "run" it? e.g. DrRacket doesn't have a "Hierarchy Panel".

**Comment by Metaxal** [comment]
I've updated the README and the wiki. Thanks for reporting it!
