### ISSUE TITLE
Closing file, Clicking Save, and Canceling freezes Hierarchy display

### ISSUE THREAD

**Issue by AMDphreak** [Metaxal/MrEd-Designer#11]
Steps:
- Create a Hierarchy
- Alt-F4 on (Hierarchy? Main?) window.
- Do you want to save? Click Yes.
- In Save File selection Window: Click Cancel.

Hierarchy freezes.
Menu buttons still work.

**Comment by Metaxal** [comment]
Thanks for the report!

I can't reproduce it for now.
Can you run MED in debug mode? From the command line:
`racket -l mred-designer -- --debug`

If an exception is raised, it should be displayed in the console.

**Comment by AMDphreak** [comment]
> 
> 
> Thanks for the report!
> 
> I can't reproduce it for now.
> Can you run MED in debug mode? From the command line:
> `racket -l mred-designer -- --debug`
> 
> If an exception is raised, it should be displayed in the console.

Yeah I'm not sure. I can't reproduce it. I was pretty tired, and I had two instances of mred-designer open that night at various times, so maybe one window froze and I closed the other?
