### ISSUE TITLE
Error caused by generating .rkt file for unsaved project.

### ISSUE THREAD

**Issue by AMDphreak** [Metaxal/MrEd-Designer#15]
Program assumes user has saved the project to a .med file when they click "generate .rkt" file. It pulls the path from the current saved file, but this doesn't exist. Log:

```
ryan@ryan-ADATA:~$ racket -l mred-designer
MrEd Designer 3.17: starting
path->complete-path: contract violation
  expected: (or/c path-for-some-system? path-string?)
  given: #f
  argument position: 2nd
  other arguments...:
   "project-127.rkt"
  context...:
   /home/ryan/.racket/6.11/pkgs/mred-designer/mred-designer/misc.rkt:38:12
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:454:6
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:505:32
   /usr/share/racket/pkgs/gui-lib/mred/private/wx/common/queue.rkt:653:3
```

Suggested solution:
show "save" dialog in the case that user has not saved the project in a .med file.

**Comment by Metaxal** [comment]
Good catch, thanks for the report. I'll take a look this weekend if I have enough time.

**Comment by Metaxal** [comment]
Should be fixed now. Thanks!

**Comment by AMDphreak** [comment]
> 
> 
> Should be fixed now. Thanks!

sweet! Didn't even see this until now
