### ISSUE TITLE
Missing columns property in list-box

### ISSUE THREAD

**Issue by DexterLagan** [Metaxal/MrEd-Designer#3]
Hi there,

  First of all, thanks so much for MrEd. It has made my UI life much easier.
I commonly use multiple columns in list-boxes, but the only property offered in MrEd is 'choices', which only allows for one column, and no headers.
I have to edit the generated code every time and add something like:
        #:lbListBox-choices
         (lbListBox-choices null)
         #:lbListBox-columns
         (lbListBox-columns (list "-"))

Once that's done, I also add a custom style to add 'column-headers, then it's easy to populate the listbox using my own little func:
; Helper function to populate a list-box control
(define (populate-listbox-w-columns listbox listbox-contents column-widths)
  (if (null? listbox-contents) null
      (begin (cond [(null? column-widths)   (for ([i (in-range 0 (length listbox-contents))]) ((curry set-column-width listbox i) 100))]                         ; If no column widths provided, use fixed default width
                   [(number? column-widths) (for ([i (in-range 0 (length listbox-contents))]) ((curry set-column-width listbox i) column-widths))]               ; If one width provided, use fixed specified width
                   [else                    (for ([i (in-range 0 (length column-widths))])    ((curry set-column-width listbox i) (list-ref column-widths i)))]) ; Else, set column widths using list
             (send/apply listbox set listbox-contents)))) 

If you could add this 'columns' property, and maybe add the 'column-headers style, it'd save me a lot of time :)

Best regards,

Dexter
Mercury Filmworks - Disney TVA

**Comment by Metaxal** [comment]
Hi,

Thanks for the feedback! I'll take a look at it this weekend.

**Comment by Metaxal** [comment]
Hi,

Thanks for the feedback!

I've just pushed a new version (3.17) where you can change the columns, and
most importantly select 'columns' and 'column-order' for keyword
initialization.
Hopefully this will make your life easier.

I've added the (not so) new styles in list-box%, in particular
column-headers.

Tell me if that solves your issue!

(If the version number at the top of the generated code is less than 3.17,
then you are running the old version)

Cheers,
Laurent

**Comment by DexterLagan** [comment]
That’s fantastic. I’ll have to get familiar with Git so I could possibly contribute. I use listboxes with columns and colours all the time in VS and Xojo, and if I want to use Racket more I’ll have to find a way to implement colours and editable cells. I’m not sure if Racket’s framework supports it, but if it does, maybe I could find a way to add it to MrEd.

Dex

**Comment by Metaxal** [comment]
Great.

I'm not sure about colors and editable cells. Maybe that would require making a compound widget yourself (I'm really not sure though).

I'm marking this as closed, but if you have any more issues feel free to open a new one.

**Comment by DexterLagan** [comment]
Thanks again, I owe you one. I’ll look into there more advanced listbox features and if I can get some extra functionalities I’ll contribute them to MrEd.

Dex

**Comment by DexterLagan** [comment]
Hi Laurent,

 

  Checking the ‘column-order’ for list-boxes prevents the frame from displaying, and returns an error when attempting to initialize :

 

ui.rkt:161:4: initialization for list-box%: contract violation

  expected: (listof exact-nonnegative-integer?)

  given: #t

 

This is the actual ui.rkt code :

 

(set! lbList1

    (new

     list-box%

     (parent tTab2)

     (label #f)

     (choices (list "First" "Second"))

     (callback lbList1-callback)

     (style

      ((λ (l) (list* (first l) (second l) (third l)))

       (list 'single 'horizontal-label '())))

     (font (list->font (list 8 #f 'default 'normal 'normal #f 'default #f)))

     (selection 0)

     (enabled #t)

     (vert-margin 2)

     (horiz-margin 2)

     (min-width 0)

     (min-height 0)

     (stretchable-width #t)

     (stretchable-height #t)

     (columns lbList1-columns)

     (column-order #t)))     <-------- expects a list, not #t

 

  No biggie, I’m using the init optional params to populate it, but it should probably be a list editor instead of a checkbox.

We’re also still missing column-headers (should be same control as the columns editor, but for headers.

 

Cheers!

 

Dexter

**Comment by DexterLagan** [comment]
Hi Laurent,

 

  My problem with column-headers might have been caused by me loading a project created in the previous version of MrEd. I’ll let you know if I find any problem. Thanks again for your help!

I realized that if one creates a project in 3.1x and open it in 3.17, the extra column checkboxes don’t appear in the list-boxes created previously. It’s probably completely normal. I deleted and added the controls again and everything shows up as intended.

 

Cheers,


Dexter

**Comment by Metaxal** [comment]
Hi Dexter,

Glad it works. Yes, the checkboxes don't appear to ensure backward compatibility. (Although that's a simplicity default, maybe I should try harder to 'import' previous projects if the new interface is different.)

The column-header thing is a bug indeed, it should accept #f or a list, but currently the property says #f or #t, which is wrong. I need to fix that. For now you can just leave the r.h.s. checkbox unchecked, and use the l.h.s. one to initialize it as an argument to your project-init function.

**Comment by DexterLagan** [comment]
Absolutely. I’ve been using the init params to setup column headers. I just finished developing an app that takes care of my business income tax, and without MrEd I would have had to use something else or be in a lot of pain. I download my account activity in CSV, and the app gives me everything I need to enter in my tax return, with a bunch of tabs showing details. Lots of fun.

 



 

Dex

**Comment by Metaxal** [comment]
Cool! Do you think you could post a snapshot of what it looks like just to
see what you do with it? :)

**Comment by DexterLagan** [comment]
Sure, I should probably upload all this to Github. First I have to clean up and organize my code, since this tax helper app was just a quick project for myself.

I’ve been very lazy with sharing my code but now I’m sitting on this big library and nobody but me benefits.

For example, I developed a shell for Racket. I called it LSH (lisp shell). It supports most commands a regular Unix shell supports, except that it also understands DOS commands. You can eval racket forms straight from the command line, and even run operations on lists of files. You can record shell scripts / macros directly from the command line too, set variables and retrieve them. I use LSH to record path walks and build automation apps for Disney. I should really post it as it’s a much simpler alternative to Rash. I have setup a github account, I just need to organize all this in projects and publish them. Your work on MrEd inspired me to do so.

 

Dex

**Comment by Metaxal** [comment]
Yeah, you should, definitely!

**Comment by DexterLagan** [comment]
Hi Laurent,

 

  I finally got around to install Git and push my first project : Lisp Shell.

https://github.com/DexterLagan/lsh

 

This is my first public project ever so please be nice.

 

Dexter

**Comment by Metaxal** [comment]
I haven't tried it yet, but that looks cool! I like particularly the
multi-OS support :)

**Comment by DexterLagan** [comment]
I found a small bug in MrEd, when opening an existing project, the previous project stub is still listed in the Hierarchy window :

 



 

Do you prefer I post any bug as an issue, or email is OK?

 

Thanks!

 

Dex

**Comment by Metaxal** [comment]
Yes, please file a new issue. Thanks!

**Comment by DexterLagan** [comment]
Will do. Cheers!

**Comment by DexterLagan** [comment]
Hi Laurent,

 

 I just published this: https://github.com/DexterLagan/provide-generator

A provide form generator  for Racket modules.

I thought I’d share.

 

Dexter

**Comment by Metaxal** [comment]
That's cool! You could easily make a [Quickscript](https://github.com/Metaxal/quickscript) script for DrRacket, which would avoid the copy/paste hassle ;)

**Comment by DexterLagan** [comment]
Sounds good. I’ll check Quickscript out. Thanks! 

Dex
